# Generated by Django 5.2.13 on 2026-05-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clause'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clause',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
