# Generated by Django 5.2.13 on 2026-05-04 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clause_explanation_clause_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contract_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_params', models.JSONField(default=list)),
                ('sol_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContractProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict)),
                ('generated_code', models.TextField(blank=True, null=True)),
                ('is_ready_for_deployment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='api.document')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.smartcontracttemplate')),
            ],
        ),
    ]
