# Generated by Django 5.2.13 on 2026-05-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_smartcontracttemplate_contractproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractproposal',
            name='client_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractproposal',
            name='client_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
