# Generated by Django 5.2.13 on 2026-05-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contractproposal_client_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractproposal',
            name='contract_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='contractproposal',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
