# Generated by Django 5.2.13 on 2026-05-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contractproposal_contract_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='fairness_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clause',
            name='fairness_score',
            field=models.FloatField(default=1.0),
        ),
    ]
