# Generated by Django 5.2.13 on 2026-05-06 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_clause_fairness_notes_clause_fairness_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='research_papers/')),
                ('abstract', models.TextField(blank=True, null=True)),
                ('methodology', models.TextField(blank=True, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_papers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
