"""
ILDLM Framework - Smart Contract Code Templates
Module: smart_contract_engine/templates.py
"""

SOLIDITY_LEGAL_CONTRACT_TEMPLATE = """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title {contract_name}
 * @dev Auto-generated legal smart contract generated by ILDLM Framework.
 * Document Reference Hash: {document_hash}
 * Governing Law: {governing_law}
 */
contract {contract_name} {{
    enum ContractState {{ Created, Active, Fulfilled, Defaulted, Terminated }}

    address public partyA; // {party_a_role}: {party_a_name}
    address public partyB; // {party_b_role}: {party_b_name}

    ContractState public currentState;
    string public constant DOCUMENT_HASH = "{document_hash}";
    string public constant GOVERNING_LAW = "{governing_law}";
    uint256 public immutable creationTimestamp;
    uint256 public totalValue;

    event StateChanged(ContractState previousState, ContractState newState);
    event PaymentExecuted(address indexed payer, address indexed payee, uint256 amount);
    event BreachReported(address indexed reporter, string reason);
    event ContractTerminated(address indexed initiator);

    modifier onlyPartyA() {{
        require(msg.sender == partyA, "ILDLM: Unauthorized access - Party A only");
        _;
    }}

    modifier onlyParties() {{
        require(msg.sender == partyA || msg.sender == partyB, "ILDLM: Unauthorized access - Contracting parties only");
        _;
    }}

    modifier inState(ContractState _state) {{
        require(currentState == _state, "ILDLM: Action not allowed in current state");
        _;
    }}

    constructor(address _partyB) payable {{
        require(_partyB != address(0), "ILDLM: Invalid counterparty address");
        partyA = msg.sender;
        partyB = _partyB;
        totalValue = msg.value;
        creationTimestamp = block.timestamp;
        currentState = ContractState.Created;
    }}

    function activateContract() external onlyPartyB inState(ContractState.Created) {{
        currentState = ContractState.Active;
        emit StateChanged(ContractState.Created, ContractState.Active);
    }}

    function executePayment() external payable onlyPartyA inState(ContractState.Active) {{
        require(msg.value > 0, "ILDLM: Payment must be greater than zero");
        payable(partyB).transfer(msg.value);
        emit PaymentExecuted(partyA, partyB, msg.value);
    }}

    function completeAgreement() external onlyParties inState(ContractState.Active) {{
        currentState = ContractState.Fulfilled;
        emit StateChanged(ContractState.Active, ContractState.Fulfilled);
    }}

    function reportBreach(string calldata reason) external onlyParties inState(ContractState.Active) {{
        currentState = ContractState.Defaulted;
        emit BreachReported(msg.sender, reason);
        emit StateChanged(ContractState.Active, ContractState.Defaulted);
    }}

    function terminateContract() external onlyParties {{
        currentState = ContractState.Terminated;
        emit ContractTerminated(msg.sender);
        emit StateChanged(currentState, ContractState.Terminated);
    }}
}}
"""

FABRIC_CHAINCODE_TEMPLATE = """package main

import (
	"encoding/json"
	"fmt"
	"github.com/hyperledger/fabric-contract-api-go/contractapi"
)

// LegalContractChaincode manages legal document state on Hyperledger Fabric
type LegalContractChaincode struct {
	contractapi.Contract
}

type LegalContract struct {
	ID            string `json:"id"`
	DocumentHash  string `json:"documentHash"`
	GoverningLaw  string `json:"governingLaw"`
	PartyA        string `json:"partyA"`
	PartyB        string `json:"partyB"`
	Status        string `json:"status"`
	CreationDate  string `json:"creationDate"`
}

func (c *LegalContractChaincode) InitContract(ctx contractapi.TransactionContextInterface, id string, docHash string, govLaw string, partyA string, partyB string) error {
	contract := LegalContract{
		ID:           id,
		DocumentHash: docHash,
		GoverningLaw: govLaw,
		PartyA:       partyA,
		PartyB:       partyB,
		Status:       "ACTIVE",
	}

	contractJSON, err := json.Marshal(contract)
	if err != nil {
		return err
	}

	return ctx.GetStub().PutState(id, contractJSON)
}

func (c *LegalContractChaincode) QueryContract(ctx contractapi.TransactionContextInterface, id string) (*LegalContract, error) {
	contractJSON, err := ctx.GetStub().GetState(id)
	if err != nil {
		return nil, fmt.Errorf("failed to read contract: %v", err)
	}
	if contractJSON == nil {
		return nil, fmt.Errorf("contract %s does not exist", id)
	}

	var contract LegalContract
	err = json.Unmarshal(contractJSON, &contract)
	if err != nil {
		return nil, err
	}

	return &contract, nil
}
"""
