// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title ClientEntityVsDeveloperEntityAgr
 * @dev Auto-generated legal smart contract generated by ILDLM Framework.
 * Document Reference Hash: 0x44b90d7e277e70b6c317891a0adb8cd1ded4ff858cf574048c2b3f956748a51d
 * Governing Law: the laws of England and Wales
 */
contract ClientEntityVsDeveloperEntityAgr {
    enum ContractState { Created, Active, Fulfilled, Defaulted, Terminated }

    address public partyA; // Client: Client Entity
    address public partyB; // Developer: Developer Entity

    ContractState public currentState;
    string public constant DOCUMENT_HASH = "0x44b90d7e277e70b6c317891a0adb8cd1ded4ff858cf574048c2b3f956748a51d";
    string public constant GOVERNING_LAW = "the laws of England and Wales";
    uint256 public immutable creationTimestamp;
    uint256 public totalValue;

    event StateChanged(ContractState previousState, ContractState newState);
    event PaymentExecuted(address indexed payer, address indexed payee, uint256 amount);
    event BreachReported(address indexed reporter, string reason);
    event ContractTerminated(address indexed initiator);

    modifier onlyPartyA() {
        require(msg.sender == partyA, "ILDLM: Unauthorized access - Party A only");
        _;
    }

    modifier onlyParties() {
        require(msg.sender == partyA || msg.sender == partyB, "ILDLM: Unauthorized access - Contracting parties only");
        _;
    }

    modifier inState(ContractState _state) {
        require(currentState == _state, "ILDLM: Action not allowed in current state");
        _;
    }

    constructor(address _partyB) payable {
        require(_partyB != address(0), "ILDLM: Invalid counterparty address");
        partyA = msg.sender;
        partyB = _partyB;
        totalValue = msg.value;
        creationTimestamp = block.timestamp;
        currentState = ContractState.Created;
    }

    function activateContract() external onlyPartyB inState(ContractState.Created) {
        currentState = ContractState.Active;
        emit StateChanged(ContractState.Created, ContractState.Active);
    }

    function executePayment() external payable onlyPartyA inState(ContractState.Active) {
        require(msg.value > 0, "ILDLM: Payment must be greater than zero");
        payable(partyB).transfer(msg.value);
        emit PaymentExecuted(partyA, partyB, msg.value);
    }

    function completeAgreement() external onlyParties inState(ContractState.Active) {
        currentState = ContractState.Fulfilled;
        emit StateChanged(ContractState.Active, ContractState.Fulfilled);
    }

    function reportBreach(string calldata reason) external onlyParties inState(ContractState.Active) {
        currentState = ContractState.Defaulted;
        emit BreachReported(msg.sender, reason);
        emit StateChanged(ContractState.Active, ContractState.Defaulted);
    }

    function terminateContract() external onlyParties {
        currentState = ContractState.Terminated;
        emit ContractTerminated(msg.sender);
        emit StateChanged(currentState, ContractState.Terminated);
    }
}
